import { Box } from "@mui/material";
import Footer from "components/Footer";
import Head from "next/head";
import { ReactNode } from "react";

type PageProps = {
    children: ReactNode;
    title?: string;
    description: string;
};

const PageContainer = ({
    title = "",
    description = "Generated by create next app",
    children,
}: PageProps) => {
    return (
        <Box>
            <Head>
                {title ? (
                    <title>{`VD | ${title}`}</title>
                ) : (
                    <title>Vincent Dizon</title>
                )}

                <meta name="description" content={description} />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box
                sx={{
                    paddingX: { xs: 5, md: 20 },
                    paddingY: { xs: 2, md: 5 },
                }}
            >
                {children}
            </Box>
            <Footer />
        </Box>
    );
};

export default PageContainer;
