import { Box } from "@mui/material";
import Head from "next/head";
import { ReactNode } from "react";

type PageProps = {
    children: ReactNode;
    props?: [];
    title?: string;
};

const PageContainer = ({ title = "", children, ...props }: PageProps) => {
    return (
        <Box>
            <Head>
                <title>{title}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box
                {...props}
                sx={{
                    backgroundColor: "#F4F4F4",
                }}
            >
                {children}
            </Box>
        </Box>
    );
};

export default PageContainer;
